### ISSUE TITLE
Quest Reset

### ISSUE THREAD

**Issue by MarkSchipper** [MarkSchipper/LevelDesign#2]
Can't reset quests

**Comment by MarkSchipper** [comment]
Fixed but not pushed!

**Comment by bugdevastator** [comment]
Also, quest giver resets (goes to default Femke) when you edit a quest

**Comment by MarkSchipper** [comment]
Yeah having a hard time fixing that, low on the list :)

**Comment by MarkSchipper** [comment]
Fixed and pushed!
